addpath('~/overleaf/thesis/ffworkspace/freefem_matlab_octave_plot-public/release-v2.0/demos/ffmatlib/');
[p,b,t,nv,nbe,nt,labels]=ffreadmesh('plots/ny-modon.msh');
vh=ffreaddata('plots/ny-modon.txt');

for i=0:1:50
    u=ffreaddata(["plots/ny-modon-simulated-" num2str(i)]);
    ffpdeplot(p,b,t,'VhSeq', vh, 
                    'XYData', u,...  
                    'CBTitle', 'Electric potential', ...
                    'CLevels', 20, ...
                    'Title', ["t=" num2str(i*0.001)], ...
                    'XLim', [-10,10],...
                    'YLim', [-9,10]);
    xlabel('Simulated dipole vortex behavior.', 'fontweight', 'bold');
    img = print('-RGBImage');
    imwrite(img, '~/adelsaleh.github.io/images/ny-modon-simulated.gif', ...
            'DelayTime', 0.1,... 
            'Compression', 'bzip',... 
            'WriteMode', 'Append');
end


